import { createDb } from "./client.js";
import { mcpCatalog } from "./schema/index.js";

const url = process.env.DATABASE_URL;
if (!url) throw new Error("DATABASE_URL is required");

const db = createDb(url);

const catalog = [
  {
    id: "github",
    name: "GitHub",
    description: "Repository management, issues, pull requests, code search, and file operations.",
    icon: "github",
    category: "dev-tools",
    npmPackage: "@modelcontextprotocol/server-github",
    transport: "stdio",
    defaultCommand: "npx",
    defaultArgs: ["-y", "@modelcontextprotocol/server-github"],
    requiredEnv: [{ key: "GITHUB_TOKEN", label: "GitHub Personal Access Token", required: true }],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/github",
    popularity: 100,
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "GitLab repository operations, merge requests, pipelines, and project management.",
    icon: "gitlab",
    category: "dev-tools",
    npmPackage: "@modelcontextprotocol/server-gitlab",
    transport: "stdio",
    defaultCommand: "npx",
    defaultArgs: ["-y", "@modelcontextprotocol/server-gitlab"],
    requiredEnv: [
      { key: "GITLAB_TOKEN", label: "GitLab Personal Access Token (api scope)", required: true },
      { key: "GITLAB_URL", label: "GitLab instance URL", required: false },
    ],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/gitlab",
    popularity: 80,
  },
  {
    id: "slack",
    name: "Slack",
    description: "Send messages, read channels, manage threads, and search workspace history.",
    icon: "slack",
    category: "communication",
    npmPackage: "@anthropic/slack-mcp",
    transport: "stdio",
    defaultCommand: "npx",
    defaultArgs: ["-y", "@anthropic/slack-mcp"],
    requiredEnv: [{ key: "SLACK_BOT_TOKEN", label: "Slack Bot User OAuth Token (xoxb-...)", required: true }],
    docsUrl: "https://github.com/anthropics/anthropic-quickstarts/tree/main/mcp-servers/slack",
    popularity: 90,
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    description: "Query databases, inspect schemas, read/write data, and manage connections.",
    icon: "database",
    category: "data",
    npmPackage: "@modelcontextprotocol/server-postgres",
    transport: "stdio",
    defaultCommand: "npx",
    defaultArgs: ["-y", "@modelcontextprotocol/server-postgres"],
    requiredEnv: [{ key: "POSTGRES_URL", label: "PostgreSQL connection string", required: true }],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
    popularity: 85,
  },
  {
    id: "brave-search",
    name: "Brave Search",
    description: "Privacy-focused web search with rich snippets, news, and local results.",
    icon: "search",
    category: "search",
    npmPackage: "@modelcontextprotocol/server-brave-search",
    transport: "stdio",
    defaultCommand: "npx",
    defaultArgs: ["-y", "@modelcontextprotocol/server-brave-search"],
    requiredEnv: [{ key: "BRAVE_API_KEY", label: "Brave Search API Key", required: true }],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search",
    popularity: 75,
  },
  {
    id: "filesystem",
    name: "Filesystem",
    description: "Read, write, search, and manage files on the local filesystem securely.",
    icon: "folder",
    category: "files",
    npmPackage: "@modelcontextprotocol/server-filesystem",
    transport: "stdio",
    defaultCommand: "npx",
    defaultArgs: ["-y", "@modelcontextprotocol/server-filesystem"],
    requiredEnv: [{ key: "ALLOWED_DIRS", label: "Comma-separated allowed directories", required: true }],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    popularity: 70,
  },
  {
    id: "google-drive",
    name: "Google Drive",
    description: "Browse, search, read, and create files in Google Drive and Docs.",
    icon: "cloud",
    category: "files",
    npmPackage: "@anthropic/gdrive-mcp",
    transport: "stdio",
    defaultCommand: "npx",
    defaultArgs: ["-y", "@anthropic/gdrive-mcp"],
    requiredEnv: [{ key: "GOOGLE_CREDENTIALS", label: "Google OAuth credentials JSON path", required: true }],
    docsUrl: "https://github.com/anthropics/anthropic-quickstarts/tree/main/mcp-servers/gdrive",
    popularity: 65,
  },
  {
    id: "puppeteer",
    name: "Puppeteer",
    description: "Browser automation — navigate, screenshot, fill forms, and extract content from web pages.",
    icon: "globe",
    category: "dev-tools",
    npmPackage: "@modelcontextprotocol/server-puppeteer",
    transport: "stdio",
    defaultCommand: "npx",
    defaultArgs: ["-y", "@modelcontextprotocol/server-puppeteer"],
    requiredEnv: [],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
    popularity: 60,
  },
  {
    id: "sentry",
    name: "Sentry",
    description: "Error tracking, issue search, release management, and performance monitoring.",
    icon: "bug",
    category: "dev-tools",
    npmPackage: "@sentry/mcp-server",
    transport: "stdio",
    defaultCommand: "npx",
    defaultArgs: ["-y", "@sentry/mcp-server"],
    requiredEnv: [{ key: "SENTRY_AUTH_TOKEN", label: "Sentry Auth Token", required: true }],
    docsUrl: "https://docs.sentry.io/product/integrations/mcp/",
    popularity: 55,
  },
  {
    id: "linear",
    name: "Linear",
    description: "Issue tracking, project management, cycles, and team workflows.",
    icon: "list",
    category: "dev-tools",
    npmPackage: "@anthropic/linear-mcp",
    transport: "stdio",
    defaultCommand: "npx",
    defaultArgs: ["-y", "@anthropic/linear-mcp"],
    requiredEnv: [{ key: "LINEAR_API_KEY", label: "Linear API Key", required: true }],
    docsUrl: "https://github.com/anthropics/anthropic-quickstarts/tree/main/mcp-servers/linear",
    popularity: 70,
  },
  {
    id: "discord",
    name: "Discord",
    description: "Channel messaging, server management, user mentions, and webhook integration.",
    icon: "message-circle",
    category: "communication",
    npmPackage: "@anthropic/discord-mcp",
    transport: "stdio",
    defaultCommand: "npx",
    defaultArgs: ["-y", "@anthropic/discord-mcp"],
    requiredEnv: [{ key: "DISCORD_BOT_TOKEN", label: "Discord Bot Token", required: true }],
    docsUrl: "https://github.com/anthropics/anthropic-quickstarts/tree/main/mcp-servers/discord",
    popularity: 50,
  },
  {
    id: "mysql",
    name: "MySQL",
    description: "MySQL database operations — queries, schema inspection, and data manipulation.",
    icon: "database",
    category: "data",
    npmPackage: "@benborla29/mcp-server-mysql",
    transport: "stdio",
    defaultCommand: "npx",
    defaultArgs: ["-y", "@benborla29/mcp-server-mysql"],
    requiredEnv: [{ key: "MYSQL_URL", label: "MySQL connection string", required: true }],
    docsUrl: "https://github.com/benborla29/mcp-server-mysql",
    popularity: 45,
  },
];

console.log("Seeding MCP catalog...");

for (const entry of catalog) {
  await db
    .insert(mcpCatalog)
    .values(entry)
    .onConflictDoUpdate({
      target: mcpCatalog.id,
      set: {
        name: entry.name,
        description: entry.description,
        icon: entry.icon,
        category: entry.category,
        npmPackage: entry.npmPackage,
        transport: entry.transport,
        defaultCommand: entry.defaultCommand,
        defaultArgs: entry.defaultArgs,
        requiredEnv: entry.requiredEnv,
        docsUrl: entry.docsUrl,
        popularity: entry.popularity,
      },
    });
}

console.log(`Seeded ${catalog.length} MCP catalog entries.`);
process.exit(0);
